Added pop(), popitem(), __reversed__(); Documented unimplemented methods
Details:

* Added pop() by delegating to the underlying dictionary. The omission
  of the 'default' argument is detected using a new constant _OMITTED
  as a default value for that parameter. The _OMITTED constant is
  defined as object(); this is an idea from CPython's datetime.timezone
  class.

  Added testcases for pop(). The same idea was used to indicate
  in the pop() testcases that an optional argument is not to be
  passed, defining an _OMIT_ARG constant. Note that this constant
  has different meaning than _OMITTED and could have been defined
  with a different value.

* Improved the testcases for get() to also use the new _OMIT_ARG
  constant for controlling whether the optional 'default' argument
  is omitted, so that the previous value used for that (None)
  could now be used as a value to be passed.

  Improved the explanatory assertion message in test_..get() to
  use new style formatting and to explicitly identify when the
  'default' parameter has been omitted in a testcase.

* Added popitem() by delegating to the underlying dictionary.

  Added testcases for popitem().

* Added __reversed__() by delegating to reversed(self.keys()).

  Implementing __reversed__() is necessary because the fall back of
  reversed() to using len() and __getitem__() (the sequence protocol")
  requires that the object is a sequence, and relying on the fallback for
  dicts results in TypeError.

  Added testcases for __reversed__(). The testcases are skipped
  when testing against a standard dict on Python versions <3.7 where it
  is not guaranteed to be ordered (because then, reversed() raises
  TypeError: "argument to reversed() must be a sequence").

* Added __reversed__() to the dict view classes.

* Documented the reasons the following methods are not implemented:

  * __getattribute__(self, name): The method inherited from object is used;
    no reason to have a different implementation.

  * __sizeof__(self): The method inherited from object is used; no reason
    to have a different implementation.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>